import "../styles/global.css";
import "../styles/slick.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { motion } from "framer-motion";

export const metadata = {
  title: "KOHM 인물 키오스크",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google" content="notranslate" />
      </head>

      <body> {children}</body>
    </html>
  );
}
